# Generated by Django 4.0.6 on 2022-12-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profiledata_excelid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='excelid',
        ),
    ]
