# Generated by Django 4.0.6 on 2022-12-10 21:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_profiledata_excelid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='money1',
        ),
        migrations.AddField(
            model_name='profiledata',
            name='excelid',
            field=models.IntegerField(null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
